python==3.12.8
pip==25.0
setuptools==75.8.0
h5py==3.12.1
numpy==2.2.2
addict==2.4.0
tqdm==4.67.1
joblib==1.4.2
pandas==2.2.3
pytorch==2.5.1
scikit-learn==1.6.1
ase==3.24.0
transformers==4.48.2
torch-ema==0.3
pyyaml==6.0.2
torch-scatter==2.1.2
e3nn==0.5.5
