Base:
  seed: 114514
  task: "q"
  Metric:
    metrics_str: ["Qa_rmse"]
    metrics_weight: [1.0]
Datahub:
  data_path: ""
  energy_bias_path: ""
  Feature:
    Ra:
      active: True
    Za:
      active: True
    Q:
      active: True
Modelhub:
  FF:
    FF01:
      active: True
      model: "PhysNet"
      feature: ["Ra", "Za", "Q"]
      loss:
        key: "mse_nh"
        params:
          weights:
            nh_loss: 1
            Qa: 1
      params:
        F: 128
        K: 64
        sr_cut: 10.0
        num_blocks: 3
        num_residual_atomic: 2
        num_residual_interaction: 2
        num_residual_output: 1
        use_electrostatic: true
        use_dispersion: true
        activation_fn: shifted_softplus
        drop_out: 0.0
        dtype: "float32"
Trainer:
  Split:
    method: "fold_random"
    params:
      seed: 114514
      n_splits: 5
  Common:
    seed: 114514
    logger_level: 1
    report: True
  FFtrainer:
    patience: 50
    max_epochs: 1
    learning_rate: 1e-3
    warmup_ratio: 0.03
    batch_size: 32
    max_norm: 5.0
    cuda: True
    amp: False