Base:
  seed: 114514
  task: "q"
Datahub:
  data_path:
  energy_bias_path:
  Feature:
    Ra:
      active: True
    Za:
      active: True
    Q:
      active: True
Modelhub:
  FF:
    FF01:
      active: True
      model: "PhysNet"
      feature: ["Ra", "Za", "Q"]
      params:
        sr_cut: 10.0
        num_blocks: 3
        num_residual_atomic: 2
        num_residual_interaction: 2
        num_residual_output: 1
        use_electrostatic: true
        use_dispersion: true
        activation_fn: shifted_softplus
        drop_out: 0.0
Trainer:
  Common:
    split_method: [0.8, 0.1, 0.1]
    split_seed: 114514
    seed: 114514
    logger_level: 1
    report: True
  FFtrainer:
    patience: 50
    max_epochs: 300
    learning_rate: 1e-3
    warmup_ratio: 0.03
    batch_size: 8
    max_norm: 5.0
    cuda: True
    amp: True