Datahub:
  data_path: "/my/dataset.pkl" # path to dataset: pickle, npz or hdf5
  data_format: pickle # pickle, npz or hdf5
  features:
    Ra: coord
    Za: atom_type
    Q:
    N: 
  targets:
    E: energy
    Fa: grad
    Qa: chrg
    Q:
    M2: dipole
  preload: false
  neighbor_list: full
  transforms:
    atomic_energy: "/my/atomic/energy.csv" # path to store atomic_energy
Modelhub:
  internal_FFs:
    FF01:
      suffix:
      architecture: PhysNet
      active: true
      loss:
        mae:
          Qa: 1
          Fa: 1
          E: 1
        nh_penalty: 0.01
      build_params:
        F: 128
        K: 64
        sr_cut: 10.0
        num_blocks: 5
        num_residual_atomic: 2
        num_residual_interaction: 3
        num_residual_output: 1
        use_electrostatic: true
        use_dispersion: true
        activation_fn: shifted_softplus
        drop_out: 0.0
        kehalf: 0.26458863 # atomic unit system 0.5 * 0.529
        d3_autoev: 1 # atomic unit system
    FF02:
      architecture: SpookyNet
      active: True
Trainer:
  Splitter:
    method: random
    parts: ["training", "validation", "test"]
    ratios: [0.7, 0.1, 0.2]
    preload: false
    save: true
    seed: 114514
  seed: 114514
  learning_rate: 0.001
  warmup_ratio: 0.1
  patience: 50
  max_norm: 1.0
  cuda: true
  weight_decay: 1e-4
  batch_size: 8
  max_epochs: 1000
  dtype: float32
Metric:
  Qa:
    rmse: 1
  Fa:
    rmse: 1
  E:
    rmse: 1