Datahub:
  data_path: "/my/dataset.pkl" # path to dataset: pickle, npz or hdf5
  data_format: pickle # pickle, npz or hdf5
  features:
    Ra: coord
    Za: atom_type
    Q:
    N: 
  targets:
    E: energy
    Fa: grad
    Qa: chrg
    Q:
    M2: dipole
  preload: false
  neighbor_list: full
  transforms:
    atomic_energy: "/my/atomic/energy.csv" # path to store atomic_energy
Modelhub:
  internal_FFs:
    FF01:
      suffix:
      architecture: PhysNet
      active: true
      loss:
        mae:
          Qa: 1
          Fa: 1
          E: 1
        nh_penalty: 0.01
      build_params:
        dim_embedding: 128
        num_rbf: 64
        max_Za: 95
        cutoff_sr: 10.0
        drop_out: 0.0
        Hartree_in_E: 1
        Bohr_in_R: 0.5291772108
      layers:
        - name: Distance
        - name: ExponentialGaussianRBF
          params: # num_rbf, cutoff_sr in build_params
            no_basis_at_infinity: false
            init_alpha: 1
            exp_weighting: false
            learnable_shape: true
            cutoff_fn: polynomial
            init_width_flavor: PhysNet
        - name: RandomAtomEmbedding # dim_embedding, max_Za in build_params
        - name: Core
          params: # dim_embedding, num_rbf, cutoff_sr in build_params; cutoff_lr as default
            num_blocks: 5
            num_residual_atomic: 2
            num_residual_interaction: 3
            num_residual_output: 1
            activation_fn: shifted_softplus
            drop_out: 0.0
        - name: AtomicAffine
          params: # max_Za in build_params
            shifts:
              Ea:
                values: 0
                learnable: true
              Qa:
                values: 0
                learnable: true
            scales:
              Ea:
                values: 1
                learnable: true
              Qa:
                values: 1
                learnable: true
        - name: ChargeConservation
        - name: AtomicCharge2Dipole
        - name: ElectrostaticEnergy # Hartree_in_E, Bohr_in_R in build_params
        - name: GrimmeD3Energy
          params: # Hartree_in_E, Bohr_in_R in build_params
            learnable: true
        - name: EnergyReduce
        - name: Force
    FF02:
      architecture: SpookyNet
      active: True
Trainer:
  Splitter:
    method: random
    parts: ["training", "validation", "test"]
    ratios: [0.7, 0.1, 0.2]
    preload: false
    save: true
    seed: 114514
  seed: 114514
  learning_rate: 0.001
  warmup_ratio: 0.1
  patience: 50
  max_norm: 1.0
  cuda: true
  weight_decay: 1e-4
  batch_size: 8
  max_epochs: 1000
  dtype: float32
Metric:
  Qa:
    rmse: 1
  Fa:
    rmse: 1
  E:
    rmse: 1