Datahub:
  data_path: "/my/dataset.pkl" # path to dataset: pickle, npz or hdf5
  data_format: pickle # pickle, npz or hdf5
  features:
    Ra: coord
    Za: atom_type
    Q:
    N: 
  targets:
    E: energy
    Fa: grad
    Qa: chrg
    Q:
    M2: dipole
  preload: false
  neighbor_list: full
  transforms:
    atomic_energy: "/my/atomic/energy.csv" # path to store atomic_energy
Modelhub:
  internal_FFs:
    FF01:
      suffix:
      architecture: PhysNet
      active: false
      loss:
        mae:
          Qa: 1
          Fa: 1
          E: 1
        nh_penalty: 
          weight: 0.01
      build_params:
        dim_embedding: 128
        num_rbf: 64
        max_Za: 94
        cutoff_sr: 10.0
        Hartree_in_E: 1
        Bohr_in_R: 0.5291772108
        cutoff_fn: polynomial
      layers:
        - name: RangeSeparation # cutoff_sr in build_params
        - name: ExponentialGaussianRBF
          params: # num_rbf, cutoff_sr, cutoff_fn in build_params
            no_basis_at_infinity: false
            init_alpha: 1
            exp_weighting: false
            learnable_shape: true
            init_width_flavor: PhysNet
        - name: RandomAtomEmbedding # dim_embedding, max_Za in build_params
        - name: Core
          params: # dim_embedding, num_rbf in build_params
            num_blocks: 5
            num_residual_atomic: 2
            num_residual_interaction: 3
            num_residual_output: 1
            activation_fn: shifted_softplus
            activation_params:
              dim_feature: 1
              initial_alpha: 1
              initial_beta: 1
              learnable: false
            dropout_rate: 0.0
        - name: AtomicAffine
          params: # max_Za in build_params
            shifts:
              Ea:
                values: 0
                learnable: true
              Qa:
                values: 0
                learnable: true
            scales:
              Ea:
                values: 1
                learnable: true
              Qa:
                values: 1
                learnable: true
        - name: ChargeConservation
        - name: AtomicCharge2Dipole
        - name: ElectrostaticEnergy # Hartree_in_E, Bohr_in_R in build_params; cutoff_lr as default
          params:
            cutoff_lr: null
            lr_flavor: simple
            half_switch: true
        - name: GrimmeD3Energy
          params: # Hartree_in_E, Bohr_in_R in build_params
            learnable: true
        - name: EnergyReduce
        - name: Force
    FF02:
      suffix:
      architecture: SpookyNet
      active: true
      build_params:
        dim_embedding: 64
        num_rbf: 16
        max_Za: 87
        cutoff_sr: 5.291772105638412
        Hartree_in_E: 1
        Bohr_in_R: 0.5291772108
      layers:
        - name: Distance
        - name: ExponentialBernsteinRBF
          params: # num_rbf, cutoff_sr in build_params
            no_basis_at_infinity: false
            init_alpha: 0.9448630629184640
            exp_weighting: false
            learnable_shape: true
            cutoff_fn: bump
        - name: NuclearEmbedding
          params: # max_Za, dim_embedding in build_params
            zero_init: true
            use_electron_config: true
        - name: ElectronicEmbedding
          params: # dim_embedding in build_params
            num_residual: 1
            activation_fn: swish
            attribute: charge
        - name: ElectronicEmbedding
          params: # dim_embedding in build_params
            num_residual: 1
            activation_fn: swish
            attribute: spin
        - name: Core
          params: # dim_embedding, num_rbf in build_params
            num_modules: 3
            num_residual_electron: 1
            num_residual_pre: 1
            num_residual_local_x: 1
            num_residual_local_s: 1
            num_residual_local_p: 1
            num_residual_local_d: 1
            num_residual_local: 1
            num_residual_nonlocal_q: 1
            num_residual_nonlocal_k: 1
            num_residual_nonlocal_v: 1
            num_residual_post: 1
            num_residual_output: 1
        - name: ZBLRepulsionEnergy # Hartree_in_E, Bohr_in_R in build_params
        - name: ElectrostaticEnergy # Hartree_in_E, Bohr_in_R in build_params; cutoff_lr as default
          params:
            lr_flavor: smooth
            half_switch: false
        - name: GrimmeD4Energy
          params: # Hartree_in_E, Bohr_in_R, max_Za in build_params
            learnable: true
Trainer:
  Splitter:
    method: random
    parts: ["training", "validation", "test"]
    ratios: [0.7, 0.1, 0.2]
    preload: false
    save: true
    seed: 114514
  seed: 114514
  learning_rate: 0.001
  warmup_ratio: 0.1
  patience: 50
  max_norm: 1.0
  cuda: true
  weight_decay: 1e-4
  batch_size: 8
  max_epochs: 1000
  dtype: float32
Metric:
  Qa:
    rmse: 1
  Fa:
    rmse: 1
  E:
    rmse: 1