Simulation:
  environment: "ase"                                # simulation environment: ase
  dtype: float64                                    # pytorch data type throughout the computation: float32 (single) / float64 (double), default float64, for better numerical behavior during optimization
  cuda: true                                        # if cuda is searched and used if possible
  task: md                                          # molecular dynamics
  idx_start_from: 1                                 # for your confusion of indices starting from 0 or 1
  neighbor_list: full                               # you want this to be the same as how the model is trained
  fs_in_t: 1
  Hartree_in_E: 1.0
  integrate:
    integrator: Langevin
    time_step: 0.5
    temperature_in_K: 300
    friction: 0.01
    n_step: 100000
System:
  structure_file: "/your/initial/configuration.xyz" # initial configuration of scanning
  charge: -1                                        # total charge of the structure
  multiplicity: 1                                   # multiplicity of the structure (only useful if the model is spin-aware)