Base:
  seed: 114514
  task: "qe"
  Metric:
    metrics_str: ["Qa_rmse", "E_rmse", "F_rmse"]
    metrics_weight: [1.0, 1.0, 100]
Datahub:
  data_path:
  energy_bias_path:
  Feature:
    Ra:
      active: True
    Za:
      active: True
    Q:
      active: True
Modelhub:
  FF:
    FF01:
      active: True
      model: "PhysNet"
      feature: ["Ra", "Za", "Q"]
      loss:
        key: "mae_nh"
        params:
          weights:
            nh_loss: 0.272
            Qa: 1.36 # 27.2 / 20
      params:
        F: 128
        K: 64
        sr_cut: 10.0
        num_blocks: 5
        num_residual_atomic: 2
        num_residual_interaction: 3
        num_residual_output: 1
        use_electrostatic: true
        use_dispersion: true
        activation_fn: shifted_softplus
        drop_out: 0.0
        kehalf: 0.26458863 # atomic unit system 0.5 * 0.529
        d3_autoev: 1 # atomic unit system
        dtype: "float32"
        cv_pretrain:
Trainer:
  Split:
    method: "train_val_test_random"
    params:
      ratio: [0.7, 0.1, 0.2]
  Common:
    seed: 114514
    logger_level: 1
    report: True
  FFtrainer:
    patience: 50
    max_epochs: 1000
    learning_rate: 1e-3
    warmup_ratio: 0.03
    batch_size: 8
    max_norm: 5.0
    weight_decay: 0.001
    cuda: True
    amp: False