Simulation:
  environment: "ase"                                # simulation environment: ase
  dtype: float64                                    # pytorch data type throughout the computation: float32 (single) / float64 (double), default float64, for better numerical behavior during optimization
  cuda: true                                        # if cuda is searched and used if possible
  task: scan                                        # simulation type: scan
  idx_start_from: 1                                 # for your confusion of indices starting from 0 or 1
  neighbor_list: full                               # you want this to be the same as how the model is trained
  constraint:
    fix_atom:
      indices: [                                    # list of indices of atoms to be fixed during constrained optimization
        1,2,3,4,5          
      ]
  optimize:
    optimizer: LBFGS                                # optimizer: LBFGS
  sampling:
    cv: "distance"                                  # reaction coordinate type: distance
    params:
      i0: 100                                       # index of the first atom
      i1: 101                                       # index of the second atom
      x0: 3.812                                     # initial value of distance between two atoms during scanning
      x1: 1.492                                     # final value of distance between two atoms during scanning
      num: 25                                       # number of scanning points
System:
  structure_file: "/your/initial/configuration.xyz" # initial configuration of scanning
  charge: -1                                        # total charge of the structure
  multiplicity: 1                                   # multiplicity of the structure (only useful if the model is spin-aware)