name: docs_Enerzyme
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton

    # Pip-only installs
  - pip:
    - numpy
    - h5py
    - tqdm
    - ase
    - joblib
    - addict
    - pandas
    - torch
    - scikit-learn
    - transformers
    - torch-ema
    - pyyaml
    - torch-scatter
    - rdkit
    - e3nn
    - pytorch-lightning
    - -e ../

